// <auto-generated />
namespace VeriStore.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Addtbl_usersTest : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addtbl_usersTest));
        
        string IMigrationMetadata.Id
        {
            get { return "201810042034021_Addtbl_usersTest"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
